config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :users, except: [:new]
  resources :posts

   root 'posts#home'

   get 'signup', to: 'users#new'

   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	 
	 belongs_to :user
	 validates :title, presence: true, length: {minimum: 3, maximum: 50}
     validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :comments
	has_many :posts
	has_secure_password

	before_save { self.email = email.downcase }

	validates :username, presence: true,
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 25 }
                VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105 },
               uniqueness: { case_sensitive: false },
               format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
 
  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
  	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
		flash[:danger] = "You must be logged in to perform that action"
		redirect_to root_path
	    end
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:description, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :require_user, only: [:home, :edit, :create, :update, :destroy]
  #before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def home
    redirect_to posts_path if logged_in?
  end

  def index
    @posts = Post.paginate(page:params[:page], per_page: 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end

   # def require_same_user
    #  if current_user != @article.user
     #   flash[:danger] = "You can only edit or delete your own articles"
      #  redirect_to root_path
      #end
    #end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create

	  user = User.find_by(email: params[:session][:email].downcase)
		 if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy

		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path

	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  #before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.paginate(page:params[:page], per_page:5)
  end


  def new
    @user = User.new
  end



  def create
    @user = User.new(user_params)
    if @user.save
      #session[:user_id] = @user.id
      flash[:success] = "Welcome to the Barebones blog #{@user.username}"
      redirect_to posts_path
    else 
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.paginate(page: params[:page], per_page:5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

private
 def user_params
   params.require(:user).permit(:username, :email, :password)
 end

 def set_user
    @user = User.find(params[:id])
  end

  #def require_same_user
   #  if current_user!= @user
    #  flash[:danger] = "You can only edit your own account"
     # redirect_to root_path
    #end
  #end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.description %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">

    <nav>
      <ul>
        <li><%#= link_to "About", about_path %></li>
      </ul>
    </nav>
 </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">×</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navi.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      	      <%= link_to "Barebones", root_path, class: "navbar-brand", id: "logo" %>


    </div>
<!-- Collect the nav links, forms, and other content for toggling -->
 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
         <li><%= link_to "New Post", new_post_path %></li>
        
	</ul>

	

	<ul class="nav navbar-nav navbar-right">
		<% if logged_in? %>
			<li><%= link_to 'Log out', logout_path, method: :delete %></li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
				<li><%= link_to "View your profile", user_path(current_user) %></li>
				
			</ul>
			</li>
		<% else %>
			<li><%= link_to 'Log in', login_path %></li>
			<li><%= link_to 'Sign up', signup_path %></li>
		<% end %>
	</ul>

	</div><!-- /.navbar-collapse -->
 
</div><!-- /.container-fluid -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barebones</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navi' %>
<%#= render 'layouts/messages' %>
<div class="container">
  <%#= yield %>
</div>
<%= render 'layouts/footer' %>
<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :title %>
          </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of the post", autofocus: true %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>

        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of post" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
      </div>
    <% end %>
  
  <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to articles listing", posts_path %> ]
  </div>
</div>
</div>

app/views/posts/_post.html.erb
<%= obj.each do |post| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="post-title">
				<%= link_to post.title, post_path(post) %>
			</div>

			<div class="post-body">
				<%= truncate(post.description, length: 100) %>
				<div class="post-meta-details">
						<small>Created by: <%= post.user.username if post.user%>,
								<%= time_ago_in_words(post.created_at) %> ago,
								last updated: <%= time_ago_in_words(post.updated_at) %> ago</small>
				</div>
			</div>
			<div class="post-actions">
				<%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this post", post_path(post), method: :delete,
				data: { confirm: "Are you sure you want to delete the post?"},
				class: "btn btn-xs btn-danger" %>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1 align= "center">Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<div class="jumbotron">
  <h1> Barebones</h1>
  <div class= signup>
    <%= link_to "Sign up now", "signup", class: "btn btn-primary btn-lg"%>
  </div>
</div>

app/views/posts/index.html.erb
<h1 align="center">Listing all posts</h1>
  <div align = "center">
    <%= will_paginate %>
  </div>

  <%= render 'post', obj: @posts %>
  

app/views/posts/new.html.erb
<h1 align="center">Create New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2 align="center">Title: <%= @post.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<% if @post.user %>
		<ul class="listing">
		<div class="row center">
			<div class="col-md-4 col-md-offset-4">
				<li>Created by:</li>
				<li class="post-title">
					<%= link_to @post.user.username, user_path(@post.user) %>
				</li>
				<li><small>
					<%= pluralize(@post.user.post.count, "post") if @post.user.post %>
				</small></li>
			</div>
		</div>
		</ul>
<% end %>

<h4 class="center description"><strong>Description:</strong></h4>
	<hr>
		<%= simple_format(@post.description) %>
			<div class="post-actions">
			   <% if logged_in? && current_user == @post.user %>
				<%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this post", post_path(@post), method: :delete,
						data: { confirm: "Are you sure you want to delete the post?"},
						class: "btn btn-xs btn-danger" %>
			    <%end%>
		
					<%= link_to "View all posts", post_path, class: "btn btn-xs btn-success" %>
			</div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
   <div class="row">
	 <div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					prohibited this article from being saved:
				</h2>
				<div class="panel-body">
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>
 

app/views/users/_form.html.erb
  <%= render 'shared/errors', obj: @user %>
  <div class='row'>
    <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>

      <div class="col-sm-8">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      </div>
    </div>

  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :email %>
    </div>
  <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
  </div>

  </div>

<div class="form-group">
  <div class="control-label col-sm-2">
    <%= f.label :password %>
  </div>

  <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
  </div>

</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?? "Sign up": "Update account", class: 'btn btn-primary btn-lg') %>
  </div>
</div>

<% end %>

<div class="col-xs-4 col-xs-offset-4">
  [ <%= link_to "Cancel request and return to articles listing", posts_path %> ]
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Barebone Bloggers</h1>
<div align="center">
  <%= will_paginate%>
  <% @users.each do |user| %>
    <ul class="listing">
    <div class="row">
       <div class="well col-md-4 col-md-offset-4">
          <li class="article-title">
              <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
       </div>
    </div>
</ul>
<% end %>
<%= will_paginate%>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Barebones</h1>
  <%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

 <%= will_paginate @user_posts %>
	
<h4 align="center"><%= @user.username %>'s posts</h4>
 <%= render "posts/post", obj: @user.posts %>

 <%= will_paginate @user_posts %>